klaytn/klaytnwallet

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

- update CONTRIBUTING and CLA link

update CONTRIBUTING and CLA link

---

public/index.html

update GA tag (GPM-156)

---

public/index.html

- Revert GA functions to previous code (keep changed ids)

WLT-191: revert ga functions (keep id alive)

---

public/index.html

restore old ga code

---

package-lock.json
package.json
src/App.js
webpack.prod.config.js

- Print git version to console.

WLT-193: Add git version

---

webpack.prod.config.js

- Add "drop console" option to webpack

add drop console to webpack options

---

webpack.prod.config.js

- merge dev branch to qa branch

add drop console to webpack options (#10)

---

klaytnwalletFront.production.js

- There is an error in Firefox that doesn't open the page because it doesn't have a JavaScript type.
- Add a statement that puts a type in the JavaScript that loads at build time.
- [ o ] Bugfix
- [ o ] I have read the [CONTRIBUTING](https://github.com/klaytn/klaytnwallet/blob/master/CONTRIBUTING.md) doc
- [ o ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytnwallet)
- [ o ] Lint and unit tests pass locally with my changes
- [  ] I have added tests that prove my fix is …

add 'js' content-type

---

src/App.js
src/components/ContentHeader.scss

- Fix the top network dropdown design.
- The same as the design of the scope.
- [ o ] New feature or enhancement
- [ o ] I have read the [CONTRIBUTING](https://github.com/klaytn/klaytnwallet/blob/master/CONTRIBUTING.md) doc
- [ o ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytnwallet)
- [ o ] Lint and unit tests pass locally with my changes

Modify network dropdown design

---

src/components/AlertPopup.js
src/components/AlertPopup.scss
src/components/KlayFaucet.js
src/components/KlayFaucet.scss

- Page UI/UX improvement work when 'faucet' is successfully received
- Expose popup on 'faucet' success.
- [ o ] New feature or enhancement
- [ o ] I have read the [CONTRIBUTING](https://github.com/klaytn/klaytnwallet/blob/master/CONTRIBUTING.md) doc
- [ o ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytnwallet)
- [ o ] Lint and unit tests pass locally with my changes
- Modifications have been made to increase the usability of the user.

Page UI/UX improvement work when 'faucet' is successfully received

---

src/components/Disclaimers.js

- change text in cypress main disclaimers
- [ o ] New feature or enhancement
- [ o ] I have read the [CONTRIBUTING](https://github.com/klaytn/klaytnwallet/blob/master/CONTRIBUTING.md) doc
- [ o ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytnwallet)
- [ o ] Lint and unit tests pass locally with my changes

change text in cypress main disclaimers

---

klaytnwalletFront.production.js
package-lock.json
package.json
src/App.js
src/components/AlertPopup.js
src/components/AlertPopup.scss
src/components/ContentHeader.scss
src/components/Disclaimers.js
src/components/KlayFaucet.js
src/components/KlayFaucet.scss
webpack.prod.config.js

baobab merge

---

.circleci/config.yml

- Add Dev, QA-baobab, QA-cypress, Prod-baobab, Prod-cypress deploy though circleci
- Automate PR git process

[circleci] Add circleci deploy workflow

---

.circleci/config.yml
.circleci/version.sh
src/components/Disclaimers.js

- Add version.sh file to check package.json version

Add version checker file

---

src/components/WalletTransfer2.js

- add value check 
- [ 0 ] Bugfix
- [0 ] I have read the [CONTRIBUTING](https://github.com/klaytn/klaytnwallet/blob/master/CONTRIBUTING.md) doc
- [ 0] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytnwallet)
- [0 ] Lint and unit tests pass locally with my changes

value check 로직 변경

---

.circleci/config.yml

- deploy with right contexts to cypress wallet

Add cypress context when production deploy

---

package.json

version up to 2.2.1

---

README.md
config/default.env
package.json
src/components/Disclaimers.js

- Api changes due to the termination of Public EN operation

Api changes due to the termination of Public EN operation

---

README.md
config/default.env

change text

---

package.json

- circleci에서 build 할 때 메모리로 인하여 에러나는 이슈 수정
- version change 2.3.0
circleci에서 node 버전을 10으로 통일해서 사용하고 있는 부분이 있어서 프론트에서 수정하였음

build error fix and version change

---

package.json
src/components/Landing.js

하단 alert 제거 작업 ( 관련 코드 삭제 )
스타일 관련 scss는 남겨두도록 변경 ( 기존 스타일이 겹치는 부분이 있어서 로딩할 수 있도록 변경 )

하단 alert 제거 작업

---

package.json
src/components/Landing.js

Reverts klaytn/klaytnwallet#44

Revert "master merge"

---

package.json
src/components/Landing.js

fix git merge error

---

.circleci/config.yml

- Update package index before deployment.

Fix deployment error from outdated package index

---

package.json

Version up to v2.4.6

---

package.json

version up to v.2.4.7

---

.circleci/config.yml

- Cloudflare is no longer used, CDN has migrated to CloudFront

Remove Cloudflare workflows in pipeline

---

src/components/AccessByPrivatekey.js
src/components/ContentHeader.scss
src/components/InputPasswordCopy.js
src/components/InputPasswordCopy.scss
src/components/Landing.scss
src/components/MyWallet.js
src/components/MyWallet.scss
src/components/WalletCreation1.scss
src/components/WalletCreationStep3.js

Fix/issues CVE-2022-32969 Mnemonic leak vulnerability

---

package.json

version up to v2.4.8

---

.github/workflows/CodeQL.yml

- Create code scanning pipeline on Github Actions

Create code scanning workflow

---

README.md

Update default README.md

---

package.json

Version up to v2.4.10

---

config/default.env
src/components/Nav.js
src/constants/url.js

In MORE section on the left panel, added below items
- Klaytn finder (Added new Environment variable KLAYTN_FINDER_URL)
- Renamed Klaytn IDE to Remix IDE

Added Klaytn Finder

---

package.json

- Version up after adding klaytn finder and updating IDE url.

Update version v2.4.11

---

.circleci/config.yml

skip CA check in signoff

---

package.json

Version up v2.4.12
